### ISSUE TITLE
Example Usage Not Using `with` Statement

### ISSUE THREAD

**Issue by engineerjoe440** [onyx-and-iris/voicemeeter-api-python#1]
First of all, this is AWESOME! I can't wait to start using this project. I've been wanting to create a little web-interface so that I could interact with VoiceMeeter on a remote server, maybe even integrate with Home Assistant. I think I'll want to use this project to give that system some legs to stand on. So kudos to you on this awesome project, and THANK YOU! I can't wait to get started.

I wanted to ask, though, do you have a recommended example for using the API outside the support of a `with` statement? Since I'm interested in using this with FastAPI as the web-server-backend, it would likely make the most sense to have a global VoiceMeeter context, or at least one per web-session, not spinning them up for _every single request_ - which would seem excessive.
Looking at the `__enter__` and `__exit__` blocks, the pattern below seems to make the most sense. Do you have other suggestions?

```python
# Base Framework Example

import voicemeeterlib
from fastapi import FastAPI

KIND = "banana"

app = FastAPI()

vm_api = voicemeeterlib.api(KIND)
vm_api.login()
vm_api.init_thread()

...

# Closing Down
#vm_api.end_thread()
#vm_api.logout()
```

Is this a reasonable approach, or would you recommend another syntax form? Thank you, again!

**Comment by onyx-and-iris** [comment]
Hello, thanks for taking an interest in the code!

Yes that seems fine. init/end thread should start/stop the observables thread so you can register an app for updates. So as long as you call login/logout only once at the start and end of your code all should work.

I hope that is helpful.

**Comment by engineerjoe440** [comment]
That's perfect, and very helpful. Thank you! When I have "something" working, I'll be sure to share with you for fun. Much appreciated! 🎉
