### ISSUE TITLE
Failing to find VoicemeeterRemote64.dll when the "UninstallString" registry key contain quotes ""

### ISSUE THREAD

**Issue by joshtews** [onyx-and-iris/voicemeeter-api-python#12]
For some reason my voicemeeter banana software will add quotes to the registry key "UninstallString" located at:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\VB:Voicemeeter {17359A74-1236-5467}
The Registy Value looks like: "C:\Program Files (x86)\VB\Voicemeeter\voicemeeterprosetup.exe"

When I try to
`import voicemeeterlib`
I get this error:
```
InstallError
Could not find "C:\Program Files (x86)\VB\Voicemeeter\VoicemeeterRemote64.dll
```
**note: the leading quote in the path**

This registry string is used in inst.py to get the path to the VoicemeeterRemote64.dll:
```
def get_vmpath():
    with winreg.OpenKey(
        winreg.HKEY_LOCAL_MACHINE, r"{}".format("\\".join((REG_KEY, VM_KEY)))
    ) as vm_key:
        return winreg.QueryValueEx(vm_key, r"UninstallString")[0]


try:
    vm_parent = Path(get_vmpath()).parent
except FileNotFoundError as e:
    raise InstallError("Unable to fetch DLL path from the registry") from e
```

It looks like inst.py is cutting off the filename and ending quote when calling .parent on the Path. This leaves it with a broken path that still has a leading quote.

I can workaround this issue by editing the registry to remove the quotes but that is not a viable production solution.

**Comment by joshtews** [comment]
I'm not 100% clear what is causing voicemeeter banana to add the quote to the registry value, but you can recreate the issue by manually editing the registry value and adding quotes.

**Comment by onyx-and-iris** [comment]
Hello, thank you for raising this issue. Can you offer any information as to how you installed Voicemeeter? Was it through the downloadable installer on the voicemeeter.com website?

I haven't noticed the installer adding quotation marks around `UninstallString` on any of my machines (I have Voicemeeter installed on about 8 different devices). I've asked the developer about this, I await a response, hopefully they can offer some insight.

**Comment by joshtews** [comment]
Thanks a bunch.
Yes I am using the installer from here: https://vb-audio.com/Voicemeeter/banana.htm
I am using version 2.1.1.1 
My OS is Windows 10 Enterprise

I wonder if it has to do with a space in the install path. Because I have it installed in "C:\Program Files (x86)\VB\Voicemeeter"
