### ISSUE TITLE
self.vm.strip[0].device.mme  ,not work,in Macro.Buttons is work fine

### ISSUE THREAD

**Issue by tjdznet** [onyx-and-iris/voicemeeter-api-python#3]
![image](https://user-images.githubusercontent.com/20569692/194988559-25bcfc82-1a10-476a-badb-d0cbe04f806c.png)

**Comment by onyx-and-iris** [comment]
Hello, thanks for raising the issue.

I've added a couple of mixin classes. I was able to test setting mme, ks and wdm driver devices. Seems to be working, couldn't verify strip asio.

device.name and device.sr for both strips/buses are now in the Device mixins.

If you have any problems or something is not working feel free to open another issue.
