### ISSUE TITLE
关于API数据更新延迟

### ISSUE THREAD

**Issue by PoWeR-Ding** [onyx-and-iris/voicemeeter-api-python#8]
你好，我遇到一个问题。

在potato程序上划动音量增益推子修改数值后，使用py获取该数值。
import voicemeeterlib

KIND_ID = "potato"
with voicemeeterlib.api(KIND_ID) as vm:
    print(vm.strip[3].gain)

但第一次获取的数值不是potato程序当前的数值，需要第二次重新运行py才能获取到potato程序当前的数值！
应该怎么解决呢？提前感谢作者

**Comment by onyx-and-iris** [comment]
Hello. I think adding a minor delay before clearing the dirty parameters should fix this. Let me know if this has helped.

**Comment by PoWeR-Ding** [comment]
> Hello. I think adding a minor delay before clearing the dirty parameters should fix this. Let me know if this has helped.

很感谢你回复这么快，问题已经解决了。感谢~
