### ISSUE TITLE
Login can raise a CAPIError if the API takes too long to respond.

### ISSUE THREAD

**Issue by onyx-and-iris** [onyx-and-iris/voicemeeter-api-python#9]
I've noticed that sometimes it's taking a bit longer than 1 second for the API to respond after a login (if it needs to start the audio engine first). This can cause {Remote}.login() to raise a CAPIError when in fact waiting a bit longer for a response succeeds.

Setting a timeout for login should fix this.

**Comment by TheMcSebi** [comment]
Hi :) Wanted to mention that I stumbled accross this while trying to resolve this occasional error.

Curiously the login function does not work when being called from a try except block and subsequent calls to the lib fail with "VBVMR_IsParametersDirty returned -1".

Now I just put the timeout in the api init call `voicemeeterlib.api(args.kind_id, timeout=60)` which should also resolve this issue.

**Comment by onyx-and-iris** [comment]
Sorry I completely missed this message, I just read it now. Whether you initialise the api with a context manager or not the default 2s value should be set for timeout here in the Remote objects constructor:

https://github.com/onyx-and-iris/voicemeeter-api-python/blob/3d56ba99b6a9fb1884cb58fe2a570eaf0866ac28/voicemeeterlib/remote.py#L39

Perhaps the default 2s wasn't enough in your case. Well, I'm glad you found the fix.
